Insere testes `test_that`
splor-mg/aux-agrupamento-dcmefo pull request #3
Opened 2024-04-23 23:34 UTC by hslinhares

[ ] teste de verificação de linhas na base execução sem agrupamento
[ ] teste verificação se  categoria `outros` está acima de 20% das linhas da base execução.
[ ] teste de verificação de linhas na base restos a pagar sem agrupamento
[ ] teste verificação se  categoria `outros` está acima de 20% das linhas da restos a pagar.

2024-04-23 23:37 UTC, hslinhares commented
@fjuniorr está com um erro na leitura do arquivo `testthat.R` em relação a `path` do arquivo de `execucao` que não consegui corrigir.

```R
Error in `FUN()`:
! In path: "C:\\projects\\aux-agrupamento-dcmefo\\checks\\rstats\\testthat\\setup.R"
Caused by error:
! File 'datapackages/siafi_2024/data/execucao.csv.gz' does not exist or is non-readable. getwd()=='C:/projects/aux-agrupamento-dcmefo/checks/rstats/testthat'
Backtrace:
     ▆
  1. ├─testthat::test_dir("checks/rstats/testthat/")
  2. │ └─testthat:::test_files(...)
  3. │   └─testthat:::test_files_serial(...)
  4. │     └─testthat:::test_files_setup_state(...)
  5. │       └─testthat::source_test_setup(".", env)
  6. │         └─testthat::source_dir(path, "^setup.*\\.[rR]$", env = env, wrap = FALSE)
  7. │           └─base::lapply(...)
  8. │             └─testthat (local) FUN(X[[i]], ...)
  9. │               └─testthat::source_file(path, env = env, chdir = chdir, wrap = wrap)
 10. │                 ├─base::withCallingHandlers(...)
 11. │                 └─base::eval(exprs, env)
 12. │                   └─base::eval(exprs, env)
 13. │                     └─data.table::fread("../datapackages/siafi_2024/data/execucao.csv.gz") at C:\projects\aux-agrupamento-dcmefo\checks\rstats\testthat\setup.R:7:1
 14. │                       └─data.table:::stopf(...) at data.table/R/fread.R:91:5
 15. │                         └─base::stop(...) at data.table/R/translation.R:8:3
 16. └─base::.handleSimpleError(...)
 17.   └─testthat (local) h(simpleError(msg, call))
 18.     └─rlang::abort(...)
 19. ```

2024-04-24 18:48 UTC, fjuniorr commented
Pra referência a solução aqui é utilizar a função [`here::here`](https://here.r-lib.org/index.html) como por exemplo [obz-dados](https://github.com/splor-mg/obz-dados/blob/eb6b5eb3e24d02d04a220564e92964b1cb219e53/checks/rstats/testthat/setup.R#L5)

2024-05-03 14:31 UTC, fjuniorr commented
@hslinhares isso está pronto pre revisão de fato?

2024-05-09 17:27 UTC, fjuniorr requested changes
@hslinhares ao tentar rodar o `make check` recebo:

```
frictionless validate datapackage.json
──────────────────────────────────────────────────────────────── Dataset ────────────────────────────────────────────────────────────────
                                   dataset                                    
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┓
┃ name                   ┃ type  ┃ path                            ┃ status  ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━┩
│ aux-agrupamento-dcmefo │ table │ data/aux-agrupamento-dcmefo.csv │ INVALID │
└────────────────────────┴───────┴─────────────────────────────────┴─────────┘
──────────────────────────────────────────────────────────────── Tables ─────────────────────────────────────────────────────────────────
                                                         aux-agrupamento-dcmefo                                                          
┏━━━━━━┳━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Row  ┃ Field ┃ Type       ┃ Message                                                                                                   ┃
┡━━━━━━╇━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ None │ None  │ hash-count │ The data source does not match the expected hash count: expected is                                       │
│      │       │            │ "50ec88d3a5fb0cc67815323c6311a57003e2b3c69943da807e33c96596f392cb" and actual is                          │
│      │       │            │ "8f9c2d67dbeb52fa50dab7547b06e2cc1dee63966feaa0f3d178069d81850cfd"                                        │
│ None │ None  │ byte-count │ The data source does not match the expected byte count: expected is "504433" and actual is "497691"       │
└──────┴───────┴────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

2024-05-09 18:00 UTC, hslinhares commented
@fjuniorr na minha o teste passou. 
Isso é porque a versão do arquivo `aux-agrupamento-dcmefo.csv` está diferente do que está apontando no `datapackage.json`. certo? Não estou entendendo porque a versão da minha máquina, no branch `checks` é a mesma do github neste mesmo branch. 
Dei um git status e retornou `up to date with` e dei um `git add -Af datapackage.json data/*.csv`, mas retornou `nothing to commit`.

2024-05-10 18:52 UTC, hslinhares commented
@fjuniorr tinha conflito de merge que resolvi, por isso não estava conseguindo rodar em sua máquina. 
Posso dar o merge ?

2024-05-10 19:10 UTC, fjuniorr commented
Pode sim

2024-05-10 19:11 UTC, merged